### ISSUE TITLE
Bug in the locking of files

### ISSUE THREAD

**Issue by VincentGardeux** [Huber-group-EMBL/rhdf5#46] opened 2019-10-30 17:53 UTC
Hello,

There is an issue with the file unlocking (at least on my machine, it is worth trying to reproduce).

To reproduce you can try to run 2 scripts in parallel:
- One is opening the h5 file in writing and keeping it open in a repeat infinite loop
- One is trying to open the h5 file in reading

At first, you run the writing script, then the reading script in parallel (another terminal for e.g.)

In principle, the writing script should lock the file, so the reading script says it cannot open the file (normal behavious).
But two bugs may arise:
- If you kill the writing process, then the file is still locked (it should not be). If you test the hdf5r library, this does not happen. This can lead to big issues since no more processes can access the file.
- Sometimes, even if properly closing the file by calling close_all(), the file is not unlocked, which leads to the same issue. Even worse if you open in reading the file, close it, and then try to open it in writing within the same script.

Do you have a solution to this problem?

**Comment by grimbough** [comment] 2019-10-31 09:57
For clarity, so I can try to track this down, are you opening and writing the files with using functions like `H5Fopen()` and `H5Dwrite()` etc or using the `h5createFile()` and `h5write()` style?

Also note that the is no `close_all()` function in **rhdf5**, although the equivalent call would be `rhdf5::h5closeAll()`.

**Comment by VincentGardeux** [comment] 2019-10-31 10:55
Hello,

Thanks for the fast consideration of this issue.
I use

handle <- H5Fopen(name = hdf5_filename, flags = mode) # mode = "H5F_ACC_RDONLY" or "H5F_ACC_RDWR"
out <- h5read(file = handle, name = dataset_path)
h5closeAll()

In other parts of the code I use h5write, h5delete, and h5createDataset. But these are not called when I have the issue.
Should I use other methods/functions for reading/closing files if using H5Fopen?

**Comment by VincentGardeux** [comment] 2019-10-31 12:27
Update:
I tried to change and use :
	handle_dataset <- H5Dopen(h5loc = handle, name = dataset_path)
	out <- H5Dread(handle_dataset)
	H5Dclose(handle_dataset)
instead of h5read()
but the problem seems to persist

**Comment by grimbough** [comment] 2019-11-05 12:59
I'm struggling to recreate this issue at the moment.  Currently I'm running the following code in a terminal to create an h5 file and start writing some content:

```r
library(rhdf5)
tf  <- "/tmp/example.h5"
if(file.exists(tf)) file.remove(tf)
h5createFile(tf)
fid1 <- H5Fopen(name = tf, flags = "H5F_ACC_RDWR") 
dat <- runif(n = 10e6)
h5write(file = fid1, obj = dat,  name = "test")
```

I then run the following in a second R session on the same machine:

```r
library(rhdf5)
tf  <- "/tmp/example.h5"
fid2 <- H5Fopen(name = tf, flags = "H5F_ACC_RDONLY")
h5read(fid2, name = "test")
```

If I leave the first session running I get the following error message when opening the file, which I think is expected:

```r
Error in H5Fopen(name = tf, flags = "H5F_ACC_RDONLY") : 
  HDF5. File accessibilty. Unable to open file.
```

If I kill the first session at this point (without properly closing the file etc) the file can be opened, but there is a new error because the write did not complete successfully and the dataset was not created  - this doesn't seem like the behaviour you're seeing.

```r
Error in h5read(fid2, name = "test") : 
  Object 'test' does not exist in this HDF5 file.
```

Can you provide a minimal example of the issue for you?  Perhaps the loop construct is important, but it shouldn't be required to keep the file handle open inside the session.

**Comment by VincentGardeux** [comment] 2019-11-08 12:46
Hello,

Thanks you for trying this out.
I created a small example for you to test:

[minimal_example.h5](http://gardeux-vincent.eu/minimal_example.h5)
[minimal_example.R](http://gardeux-vincent.eu/minimal_example.R)

I basically open the file, close it, and try to reopen it in writing mode.
The file is locked and cannot be reopen (you can wait as much as you want).
I tried with close_all() as well and the problem persists.

The "funny" stuff, is that depending of what you try to extract in the reading part of the code, sometimes it works...

Please tell me if this example works for you?

Cheers

**Comment by kevinblighe** [comment] 2019-11-15 18:49
I think that this may relate to this previously-reported issue: https://github.com/pachterlab/kallisto/issues/171

The error for me appears when I use *tximport* for Kallisto-derived H5 files. One file can always be read, but then an error is thrown on the second. If I re-run the code, a different message appears:

```
txi <- tximport(
+   as.character(c(files, files_batch1)),
+   type="kallisto",
+   txIn=TRUE,
+   txOut=FALSE,
+   tx2gene=TranscriptToGeneMap,
+   countsFromAbundance="no")
1 2 Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.


txi <- tximport(
+   as.character(c(files, files_batch1)),
+   type="kallisto",
+   txIn=TRUE,
+   txOut=FALSE,
+   tx2gene=TranscriptToGeneMap,
+   countsFromAbundance="no")
1 2 Error in H5Dread(h5dataset = h5dataset, h5spaceFile = h5spaceFile, h5spaceMem = h5spaceMem,  : 
  HDF5. Dataset. Read failed.
Além disso: Warning messages:
1: In h5checktypeOrOpenLoc(file, readonly = TRUE, native = native) :
  An open HDF5 file handle exists. If the file has changed on disk meanwhile, the function may not work properly. Run 'h5closeAll()' to close all open HDF5 object handles.
2: In h5checktypeOrOpenLoc(file, readonly = TRUE, native = native) :
  An open HDF5 file handle exists. If the file has changed on disk meanwhile, the function may not work properly. Run 'h5closeAll()' to close all open HDF5 object handles.
3: In h5checktypeOrOpenLoc(file, readonly = TRUE, native = native) :
  An open HDF5 file handle exists. If the file has changed on disk meanwhile, the function may not work properly. Run 'h5closeAll()' to close all open HDF5 object handles.
4: In h5checktypeOrOpenLoc(file, readonly = TRUE, native = native) :
  An open HDF5 file handle exists. If the file has changed on disk meanwhile, the function may not work properly. Run 'h5closeAll()' to close all open HDF5 object handles.
5: In h5checktypeOrOpenLoc(file, readonly = TRUE, native = native) :
  An open HDF5 file handle exists. If the file has changed on disk meanwhile, the function may not work properly. Run 'h5closeAll()' to close all open HDF5 object handles.
```
.

```
sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=pt_BR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=pt_BR.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=pt_BR.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rhdf5_2.28.1       tximport_1.12.3    readr_1.3.1        data.table_1.12.6 
[5] RColorBrewer_1.1-2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3      zeallot_0.1.0   crayon_1.3.4    R6_2.4.1       
 [5] backports_1.1.5 pillar_1.4.2    rlang_0.4.1     vctrs_0.2.0    
 [9] Rhdf5lib_1.6.3  hms_0.5.2       compiler_3.6.1  pkgconfig_2.0.3
[13] tibble_2.1.3
```

---------------------------------
----------------------

Update:
-----------
To add further information to this: the error is only thrown for h5 files generated on a new server that I am using. No error is thrown for older h5 files generated on other servers.

I am continuing to debug...

**Comment by VincentGardeux** [comment] 2019-11-15 19:51
Hi,

Here in my example it is important to note that if you try to open the file in reading mode the second time, everything works.

That is why I strongly believe that the issue is coming from the locking of the file, i.e. the handles on the file which are probably not properly closed.

Also, I can say that it **does not** come from 
- the OS: because this occurs on Windows and Linux
- the hdf5 library: because I use the same library with Java and it works well
- the R version: because using another package in R (hdf5r for not naming it), it works

Also as I said before, in my hands the behavior is very weird. It seems to work fine when reading some datasets, and failing with other datasets. From what I'm seeing, it seem to fail mainly when I try to read arrays of variable length strings (but maybe I'm seeing things). Could be interesting to test the same code with different datasets.

Cheers

**Comment by VincentGardeux** [comment] 2019-11-19 12:36
Hello,

I did more tests on the little example files I provided: [minimal_example.h5](http://gardeux-vincent.eu/minimal_example.h5)

I got down to a very simple code example:

```r
### Libraries
require(rhdf5)

### Open the existing HDF in read-only mode and recuperate some data
data.h5 <- H5Fopen(name = "minimal_example.h5", flags = "H5F_ACC_RDONLY")
handle_dataset <- H5Dopen(h5loc = data.h5, name = "/row_attrs/Accession")
data.ens <- H5Dread(handle_dataset)
H5Dclose(handle_dataset)
H5Fclose(data.h5)

# Open Loom in writing mode for writing results
data.h5 <- H5Fopen(name = "minimal_example.h5", flags = "H5F_ACC_RDWR") 
# This fails with error: Error in H5Fopen(name = "minimal_example.h5", flags = "H5F_ACC_RDWR") : HDF5. File accessibilty. Unable to open file.
```

This example fails on my file.

The issue seems to come **ONLY** from the Variable Length String (VLString) datasets.
You can play with it and try to open different dataset (such as /matrix or /row_attrs/_Sum in my hdf5 file), and you will see that the problem does not occur. So if you read another dataset (not variable length string), it works.

Now, if you try to open a VLString dataset in RDONLY **BEFORE** opening it in RDWR mode. the file is blocked and you cannot reopen it for the rest of your session.
However, if you open the file in RDWR the first time (and reading any VLString dataset), then it works for the whole session, even when opening other VLString datasets (here /row_attrs/Gene and /row_attrs/Accession for e.g.)

So it seems that:
- Depending on the dataset (here VL string) you may have no issue. Here it seems to fail only with the VL string datasets.
- If you **first** read any VL String dataset in RDWR mode, then it never fails again with any other VL String dataset during the length of your session.
- If you **first** read any VL String dataset in RDONLY mode, then the file is blocked forever in this session (you need to restart the session) and you cannot reopen it (but the reading worked, and contains the correct strings)

I don't know if this is the same issue than @kevinblighe but at least it narrowed down the problem in my case.
Do you see why there is this behaviour @grimbough ?

Cheers

**Comment by kevinblighe** [comment] 2019-11-19 13:34
I am not sure, @VincentGardeux .

In my case, I recently moved to a new system (Amazon Linux AMI) and I found that Kallisto was producing h5 files that were **_not_** readable by _rhdf5_. However, if I created a Conda environment on this system, then it functioned okay. In the Conda environment, I simply installed:

- hdf5-1.10.5
- kallisto-0.46.0

**Comment by grimbough** [comment] 2019-11-19 21:10
@VincentGardeux Thank you very much for digging into this further.  I've had a few other deadlines in the past week, but I'll try and take a look at this in more detail tomorrow.  Your investigations should be really helpful in tracking this down.

@kevinblighe I remember at one point kallisto was producing files created with HDF5 version 1.10 and rhdf5 was shipping with HDF5 version 1.8 which was incompatible.  I don't know if that's the cause of the issues you were seeing, but rhdf5 has been compiled with 1.10 for a while now and should be backwards compatible with older libraries - but it is of course tied to the version of Bioconductor you're using.

**Comment by grimbough** [comment] 2019-11-21 10:11
> - Depending on the dataset (here VL string) you may have no issue. Here it seems to fail only with the VL string datasets.
>  - If you first read any VL String dataset in RDWR mode, then it never fails again with any other VL String dataset during the length of your session.
>  - If you first read any VL String dataset in RDONLY mode, then the file is blocked forever in this session (you need to restart the session) and you cannot reopen it (but the reading worked, and contains the correct strings)

This is certainly odd, and I haven't found the cause yet.  I can confirm that I see the same behaviour you described above on my machine, where a specific set of options leads to the locked file this, but most others work.

So far I've written a completely separate C program to read from your file, which I can't get to show this behaviour, and then a second C application to write out my own dataset with variable length strings, which **rhdf5** seem to work fine with.

One thing I have noticed is that **h5dump** (the HDF5 application, not the R function) doesn't seem to recognise the datatype of the problem datasets e.g.

```bash
$ h5dump -H -N /row_attrs/Accession minimal_example.h5
HDF5 "/home/msmith/Downloads/minimal_example.h5" {
DATASET "/row_attrs/Accession" {
   DATATYPE  "/#1832"
   DATASPACE  SIMPLE { ( 23469 ) / ( 23469 ) }
}
}
```

For my own VL String dataset it looks like this:

```bash
HDF5 "/home/msmith/code/variable-length-strings/uvlstr.h5" {
DATASET "/Space1" {
   DATATYPE  H5T_STRING {
      STRSIZE H5T_VARIABLE;
      STRPAD H5T_STR_NULLTERM;
      CSET H5T_CSET_ASCII;
      CTYPE H5T_C_S1;
   }
   DATASPACE  SIMPLE { ( 9 ) / ( H5S_UNLIMITED ) }
}
}
```

I've no idea why this might be the case or if it could be related, so I've open a question at https://forum.hdfgroup.org/t/dataset-with-unknown-datatype/6413 - hopefully someone will be able to identify why this might be happening.

**Comment by grimbough** [comment] 2019-11-22 10:39
I think I have tracked this down.  `_H5Dread` was making a copy of the datatype, and then this was never closed, which led to an object in the file still being open.  The default behaviour of `H5Fclose()` in this scenario is:

> Access to file identifier is terminated; actual file close is delayed until all objects in file are closed

and so I guess it was never properly closed.  I don't know why the behaviour seemed to only manifest with this very specific set of opening parameters and dataset types, because it was definitely a bug in the code, but hopefully the problem is fixed.

Can you install the patched version with 
```
BiocManager::install("grimbough/rhdf5", ref = "file_lock_issues")
``` 
and confirm if it's working for you now.

**Comment by VincentGardeux** [comment] 2019-11-25 14:36
Hello,

It seems to work perfectly now!
Thanks for solving this.
It just prints some "here" debug code, but works indeed :)

Do you plan to keep it as a separate branch or merge it into the main branch?

Thank you!

Cheers

**Comment by grimbough** [comment] 2019-11-25 14:43
That's great, thanks for confirming that it works for you.  

I'll remove that remaining print statement and then merge the fix.  Since this was a clear bug I'll add it to both the devel and release branches at Bioconductor.  It'll take a couple of days to propagate through, but should be available after that.

**Closed as completed** 2019-11-25 14:53 UTC
